/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as usdcMockSol from "./USDCMock.sol";
export type { usdcMockSol };
export type { GroupSplit } from "./GroupSplit";
