name: Hardhat Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
    build:
      defaults:
        run:
          working-directory: ./backend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup NodeJS 20.12.2
              uses: actions/setup-node@v2
              with:
                node-version: 20.12.2
                cache: npm
            - name: Show NodeJS version 
              run: npm --version
            
            - name: Install Hardhat
              run: npm install --save-dev hardhat@2.22.6
            
            - name: Install Hardhat Dependencies
              run: npm ci
            
            - name: Run Hardhat Test
              run: npx hardhat test